=== tyut-pengkai/ruoyi-vue-new/om-hybase/src/main/resources/hybase/trshybase-mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:tns="http://www.huisituo.com/dms/trshybase-mapping"
        targetNamespace="http://www.huisituo.com/dms/trshybase-mapping"
        elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema">


    <element name="trshybase-mapping" type="tns:TrsHybaseMappingType"/>
    <complexType name="TrsHybaseMappingType">
        <sequence>
            <element name="class" type="tns:ClassType" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="ClassType">
        <sequence>
            <element name="property" type="tns:ClassPropertyType" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="id" type="string" use="required"/>
        <attribute name="name" type="string" use="required"/>
        <attribute name="table" type="string" use="required"/>
        <attribute name="extends" type="string"/>
    </complexType>
    <complexType name="ClassPropertyType">
        <sequence>
            <element name="extractor" type="tns:BeanType" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="name" type="string" use="required"/>
        <attribute name="column" type="string"/>
        <attribute name="uuid" type="boolean"/>
        <attribute name="highlighter" type="boolean"/>
    </complexType>
    <complexType name="BeanType">
        <attribute name="type" type="string" use="required"/>
    </complexType>

</schema>

=== tyut-pengkai/ruoyi-vue-new/om-hybase/src/main/resources/hybase/TbYqBean.thm.xml
<?xml version="1.0" encoding="UTF-8"?>
<trshybase-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns="http://www.huisituo.com/dms/trshybase-mapping"
                   xsi:schemaLocation="http://www.huisituo.com/dms/trshybase-mapping trshybase-mapping.xsd">
    <class id="yuqing.stat" name="com.trs.common.hybase.domain.TbYqBean" table="tbyx_yuqing">
        <property name="uuid" uuid="true"/>
        <property name="rid" column="RID"/>
    </class>

    <class id="yuqing.all" name="com.trs.common.hybase.domain.TbYqBean" table="tbyx_yuqing">
        <property name="uuid" uuid="true"/>
        <property name="rid" column="RID"/>
        <property name="urlTitle" column="URLTITLE"/>
        <property name="abstracts" column="ABSTRACTS"/>
        <property name="urlContent" column="URLCONTENT"/>
        <property name="source" column="SOURCE"/>
        <property name="urlName" column="URLNAME"/>
        <property name="pubTime" column="PUBTIME"/>
        <property name="loadTime" column="LOADTIME"/>
        <property name="illegalName" column="ILLEGAL_NAME"/>
        <property name="illegalType" column="ILLEGAL_TYPE"/>
        <property name="illegalObject" column="ILLEGAL_OBJECT"/>
        <property name="illegalDate" column="ILLEGAL_DATE"/>
        <property name="introduction" column="INTRODUCTION"/>
        <property name="reportDept" column="REPORT_DEPT"/>
        <property name="punishAccording" column="PUNISH_ACCORDING"/>
        <property name="punishResult" column="PUNISH_RESULT"/>
    </class>
</trshybase-mapping>

=== tyut-pengkai/ruoyi-vue-new/om-hybase/src/main/resources/hybase/BidKnowledgeBean.thm.xml
<?xml version="1.0" encoding="UTF-8"?>
<trshybase-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns="http://www.huisituo.com/dms/trshybase-mapping"
                   xsi:schemaLocation="http://www.huisituo.com/dms/trshybase-mapping trshybase-mapping.xsd">
    <class id="BidKnowledgeBean.stat" name="com.trs.common.hybase.domain.BidKnowledgeBean" table="tbyx_zcfg">
        <property name="uuid" uuid="true"/>
        <property name="id" column="ID"/>
    </class>

    <class id="BidKnowledgeBean.select" name="com.trs.common.hybase.domain.BidKnowledgeBean" table="tbyx_zcfg">
        <property name="uuid" uuid="true"/>
        <property name="id" column="ID"/>
        <property name="title" column="TITLE"/>
        <property name="content" column="CONTENT"/>
    </class>
</trshybase-mapping>

=== tyut-pengkai/ruoyi-vue-new/om-hybase/src/main/resources/hybase/EnterpriseInfoBean.thm.xml
<?xml version="1.0" encoding="UTF-8"?>
<trshybase-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns="http://www.huisituo.com/dms/trshybase-mapping"
                   xsi:schemaLocation="http://www.huisituo.com/dms/trshybase-mapping trshybase-mapping.xsd">

    <class id="EnterpriseInfo.all" name="com.trs.common.hybase.domain.EnterpriseInfoBean" table="tbyx_enterprise_info">
        <property name="id" column="id"/>
        <property name="recId" column="rec_id"/>
        <property name="eid" column="eid"/>
        <property name="entName" column="ent_name"/>
        <property name="usccCode" column="uscc_code"/>
        <property name="regNo" column="reg_no"/>
        <property name="nacaoCode" column="nacao_code"/>
        <property name="entTypeCode" column="ent_type_code"/>
        <property name="abuItem" column="abu_item"/>
        <property name="cbuItem" column="cbu_item"/>
        <property name="opFromDate" column="op_from_date"/>
        <property name="opToDate" column="op_to_date"/>
        <property name="postalCode" column="postal_code"/>
        <property name="esDate" column="es_date"/>
        <property name="apprDate" column="appr_date"/>
        <property name="regOrg" column="reg_org"/>
        <property name="entStatusCode" column="ent_status_code"/>
        <property name="regCap" column="reg_cap"/>
        <property name="regCapCurCode" column="reg_cap_cur_code"/>
        <property name="opScope" column="op_scope"/>
        <property name="opForm" column="op_form"/>
        <property name="opScoandForm" column="op_scoand_form"/>
        <property name="ptbusScope" column="ptbus_scope"/>
        <property name="domAddr" column="dom_addr"/>
        <property name="recCap" column="rec_cap"/>
        <property name="corporationName" column="corporation_name"/>
        <property name="corporationTitle" column="corporation_title"/>
        <property name="canDate" column="can_date"/>
        <property name="revDate" column="rev_date"/>
        <property name="ancheYearDate" column="anche_year_date"/>
        <property name="regionId" column="region_id"/>
        <property name="nicId" column="nic_id"/>
        <property name="lat" column="lat"/>
        <property name="lng" column="lng"/>
        <property name="updateTime" column="update_time"/>
        <property name="deleteFlg" column="delete_flg"/>
        <property name="deleteTime" column="delete_time"/>
    </class>

    <!-- 简化查询映射 -->
    <class id="EnterpriseInfo.basic" name="com.trs.common.hybase.domain.EnterpriseInfoBean"
           table="tbyx_enterprise_info">
        <property name="recId" column="rec_id"/>
        <property name="entName" column="ent_name"/>
        <property name="usccCode" column="uscc_code"/>
        <property name="regNo" column="reg_no"/>
        <property name="domAddr" column="dom_addr"/>
    </class>
</trshybase-mapping>

=== tyut-pengkai/ruoyi-vue-new/om-hybase/src/main/resources/hybase/BidExpertBean.thm.xml
<?xml version="1.0" encoding="UTF-8"?>
<trshybase-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns="http://www.huisituo.com/dms/trshybase-mapping"
                   xsi:schemaLocation="http://www.huisituo.com/dms/trshybase-mapping trshybase-mapping.xsd">

    <class id="BidExpertBean.all" name="com.trs.common.hybase.domain.BidExpertBean" table="tbyx_bid_expert">
        <property name="rid" column="RID"/>
        <property name="pubTime" column="PUBTIME"/>
        <property name="projectNo" column="PROJECT_NO"/>
        <property name="projectName" column="PROJECT_NAME"/>
        <property name="industry" column="INDUSTRY"/>
        <property name="category" column="CATEGORY"/>
        <property name="buyer" column="BUYER"/>
        <property name="buyerProvince" column="BUYER_PROVINCE"/>
        <property name="buyerCity" column="BUYER_CITY"/>
        <property name="buyerCounty" column="BUYER_COUNTY"/>
        <property name="agent" column="AGENT"/>
        <property name="sourceExpert" column="SOURCE_EXPERT"/>
        <property name="expert" column="EXPERT"/>
        <property name="sortMark" column="SORT_MARK"/>
        <property name="isIllegal" column="IS_ILLEGAL"/>
    </class>

</trshybase-mapping>

=== tyut-pengkai/ruoyi-vue-new/om-hybase/src/main/resources/hybase/OmAccountBean.thm.xml
<?xml version="1.0" encoding="UTF-8"?>
<trshybase-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns="http://www.huisituo.com/dms/trshybase-mapping"
                   xsi:schemaLocation="http://www.huisituo.com/dms/trshybase-mapping trshybase-mapping.xsd">

    <!--微博-->
    <class id="OmWeibo.account" name="com.trs.common.hybase.domain.OmAccountBean" table="trsom_weibo_accountinfo">

        <property name="sid" column="SID"/>
        <property name="uid" column="IR_UID"/>
        <property name="irScreenName" column="IR_SCREEN_NAME"/>
        <property name="irDescription" column="IR_DESCRIPTION"/>
        <property name="gender" column="IR_GENDER"/>
        <property name="friends" column="IR_FRIENDS_COUNT"/>
        <property name="fans" column="IR_FOLLOWERS_COUNT"/>
        <property name="statusCount" column="IR_STATUES_COUNT"/>
        <property name="verified" column="IR_VERIFIED"/>
        <property name="loadTime" column="LOADTIME"/>
        <property name="registerTime" column="IR_REGISTERDATA"/>
        <property name="irProfileImageUrl" column="IR_PROFILE_IMAGE_URL"/>

    </class>

    <!--微信-->
    <class id="OmWeixin.account" name="com.trs.common.hybase.domain.OmAccountBean"
           table="trsom_weixin_accountinfo">

        <property name="sid" column="SID"/>
        <property name="irWeiXinId" column="IR_WEIXINID"/>
        <property name="irScreenName" column="IR_WEIXINNAME"/>
        <property name="irDescription" column="IR_WEIXININFO"/>
        <property name="irProfileImageUrl" column="IR_PROFILE_IMAGE_URL"/>
        <property name="irIsVerified" column="IR_ISVERIFIED"/>
        <property name="irVerifyInfo" column="IR_VERIFYINFO"/>
        <property name="irVerifyDate" column="IR_VERIFYDATE"/>


    </class>
    <!--头条-->
    <class id="OmToutiao.account" name="com.trs.common.hybase.domain.OmAccountBean"
           table="trsom_toutiao_accountinfo">

        <property name="sid" column="SID"/>
        <property name="irMid" column="IR_MID"/>
        <property name="irScreenName" column="IR_SCREEN_NAME"/>
        <property name="irDescription" column="IR_DESCRIPTION"/>
        <property name="friends" column="IR_FRIENDS_COUNT"/>
        <property name="fans" column="IR_FOLLOWERS_COUNT"/>
        <property name="irIsVerified" column="IR_ISVERIFIED"/>
        <property name="irVerifyInfo" column="IR_VERIFYINFO"/>
        <property name="loadTime" column="LOADTIME"/>
        <property name="irDomain" column="IR_DOMAIN"/>
        <property name="irProfileImageUrl" column="IR_PROFILE_IMAGE_URL"/>

    </class>

    <class id="OmSocial.account" name="com.trs.common.hybase.domain.OmAccountBean"
           table="trsom_socia_accountinfos">

        <property name="sid" column="SID"/>
        <property name="irUserId" column="IR_USERID"/>
        <property name="irUserNameZH" column="IR_USERNAME_ZH"/>
        <property name="irUserNameEN" column="IR_USERNAME_EN"/>
        <property name="irUserUrl" column="IR_USER_URL"/>
        <property name="irDescription" column="IR_DESCRIPTION"/>
        <property name="irUserInfoType" column="IR_USER_INFOTYPE"/>
        <property name="fans" column="IR_FANSCOUNT"/>
        <property name="irUserSchool" column="IR_USER_SCHOOL"/>
        <property name="irUserDegree" column="IR_USER_DEGREE"/>
        <property name="irUserMajor" column="IR_USER_MAJOR"/>
        <property name="irUserCompany" column="IR_USER_COMPANY"/>
        <property name="irUserJobDuration" column="IR_USER_JOBDURATION"/>
        <property name="irUserMD5" column="IR_USERMD5"/>
        <property name="syToChinaAttitude" column="SY_TOCHIAN_ATTITUDE"/>
        <property name="syPoliticalIdent" column="SY_POLITICAL_IDENT"/>
        <property name="irCreateDate" column="IR_CREATEDATE"/>
        <property name="irEmail" column="IR_EMAIL"/>
        <property name="irAuThen" column="IR_AUTHEN"/>
        <property name="irAuThenDes" column="IR_AUTHEN_DES"/>
        <property name="irWorkJob" column="IR_WORKJOB"/>
        <property name="irWorkJob" column="IR_WORKJOB"/>
        <property name="irUserInfoType" column="IR_USER_INFOTYPE"/>


    </class>

</trshybase-mapping>
